export const colors = [
  { name: "Schwarz", value: "#1a1a1a" },
  { name: "Rot", value: "#e63946" },
  { name: "Gelb", value: "#f4a261" },
  { name: "Blau", value: "#457b9d" },
  { name: "Grau", value: "#6c757d" },
  { name: "Lila", value: "#9b5de5" },
  { name: "Weiß", value: "#ffffff" },
  { name: "Deutschland Farben", value: "linear-gradient(135deg, #000000 33%, #dd0000 33%, #dd0000 66%, #ffce00 66%)" },
  { name: "Grün", value: "#2a9d8f" },
  { name: "Hell Grün", value: "#81b29a" },
  { name: "Dunkel Grün", value: "#15616d" },
  { name: "Hell Blau", value: "#a8dadc" },
  { name: "Dunkel Blau", value: "#1d3557" }
];
export const groups = {
  A: ["Mexiko", "Südafrika", "Südkorea", "Tschechien"],
  B: ["Kanada", "Bosnien-Herzegowina", "Katar", "Schweiz"],
  C: ["Brasilien", "Marokko", "Haiti", "Schottland"],
  D: ["USA", "Paraguay", "Australien", "Türkei"],
  E: ["Deutschland", "Curaçao", "Elfenbeinküste", "Ecuador"],
  F: ["Niederlande", "Japan", "Schweden", "Tunesien"],
  G: ["Belgien", "Ägypten", "Iran", "Neuseeland"],
  H: ["Spanien", "Kap Verde", "Saudi-Arabien", "Uruguay"],
  I: ["Frankreich", "Senegal", "Irak", "Norwegen"],
  J: ["Argentinien", "Algerien", "Österreich", "Jordanien"],
  K: ["Portugal", "DR Kongo", "Usbekistan", "Kolumbien"],
  L: ["England", "Kroatien", "Ghana", "Panama"]
};
export const matches = [
  { id: 1, date: "11.06.2026", team1: "Mexiko", team2: "Südafrika", location: "Mexico City", group: "A" },
  { id: 2, date: "11.06.2026", team1: "Südkorea", team2: "Tschechien", location: "Guadalajara", group: "A" },
  { id: 3, date: "12.06.2026", team1: "Kanada", team2: "Bosnien-Herzegowina", location: "Toronto", group: "B" },
  { id: 4, date: "12.06.2026", team1: "Katar", team2: "Schweiz", location: "Vancouver", group: "B" },
  { id: 5, date: "12.06.2026", team1: "Brasilien", team2: "Marokko", location: "Miami", group: "C" },
  { id: 6, date: "12.06.2026", team1: "Haiti", team2: "Schottland", location: "New York", group: "C" },
  { id: 7, date: "13.06.2026", team1: "USA", team2: "Paraguay", location: "Los Angeles", group: "D" },
  { id: 8, date: "13.06.2026", team1: "Australien", team2: "Türkei", location: "Dallas", group: "D" },
  { id: 9, date: "13.06.2026", team1: "Deutschland", team2: "Curaçao", location: "Miami", group: "E" },
  { id: 10, date: "13.06.2026", team1: "Elfenbeinküste", team2: "Ecuador", location: "New York", group: "E" },
  { id: 11, date: "14.06.2026", team1: "Niederlande", team2: "Japan", location: "Los Angeles", group: "F" },
  { id: 12, date: "14.06.2026", team1: "Schweden", team2: "Tunesien", location: "Dallas", group: "F" },
  { id: 13, date: "14.06.2026", team1: "Belgien", team2: "Ägypten", location: "Toronto", group: "G" },
  { id: 14, date: "14.06.2026", team1: "Iran", team2: "Neuseeland", location: "Vancouver", group: "G" },
  { id: 15, date: "15.06.2026", team1: "Spanien", team2: "Kap Verde", location: "Mexico City", group: "H" },
  { id: 16, date: "15.06.2026", team1: "Saudi-Arabien", team2: "Uruguay", location: "Guadalajara", group: "H" },
  { id: 17, date: "15.06.2026", team1: "Frankreich", team2: "Senegal", location: "Miami", group: "I" },
  { id: 18, date: "15.06.2026", team1: "Irak", team2: "Norwegen", location: "New York", group: "I" },
  { id: 19, date: "16.06.2026", team1: "Argentinien", team2: "Algerien", location: "Los Angeles", group: "J" },
  { id: 20, date: "16.06.2026", team1: "Österreich", team2: "Jordanien", location: "Dallas", group: "J" },
  { id: 21, date: "16.06.2026", team1: "Portugal", team2: "DR Kongo", location: "Toronto", group: "K" },
  { id: 22, date: "16.06.2026", team1: "Usbekistan", team2: "Kolumbien", location: "Vancouver", group: "K" },
  { id: 23, date: "17.06.2026", team1: "England", team2: "Kroatien", location: "Miami", group: "L" },
  { id: 24, date: "17.06.2026", team1: "Ghana", team2: "Panama", location: "New York", group: "L" }
];